-- =============================================================================================
-- COMMISSION: the rate table, the run, the payment sheet, and the CLEARED stamp.
-- =============================================================================================
--   Finance SOP A.1  "Receive the daily (9:00 AM) and monthly (1st day of the following month)
--                     commission schedule/report generated by the system"
--   Finance SOP A.2  "Verify each RSM/agent's commission against sales records ... using the
--                     WATU data dashboard"
--   Finance SOP A.3  "Cross-check that each phone being paid for is correctly linked to the
--                     agent who sold it, before approving payment"
--   Finance SOP A.4  "Compile the full commission payment sheet and forward it to the
--                     Administration approval group for sign-off. The payment sheet must
--                     include: agent name, sales quantity, commission amount, phone number,
--                     and the RSM the agent falls under"
--   Finance SOP A.6  "mark the payment as 'cleared' in the system IMMEDIATELY, to prevent
--                     duplicate payment"
--   Finance SOP A    the Commission Audit Checklist, filed against every payment cycle
--
-- THE WHOLE POINT OF THIS FILE IS A6. Everything else here is arithmetic that could be done in
-- a spreadsheet; what a spreadsheet cannot do is refuse to pay the same period twice. A run is
-- UNIQUE per (period, kind), and once it carries cleared_at nothing can pay it again.
--
-- A RUN IS A SNAPSHOT, NOT A VIEW. The lines are written down when the run is built, because a
-- payment sheet that silently re-computes itself is a sheet nobody can audit: the figure signed
-- off on Tuesday must still be the figure on Friday, even after another deck upload lands.
-- Rebuilding is allowed while the run is a draft and refused once anybody has signed it.
--
-- Safe to run more than once.
-- =============================================================================================

-- ---------------------------------------------------------------------------------------------
-- 1. WHAT A PHONE EARNS. By role and by model, because a team leader and a field officer are
--    not paid the same for the same handset.
-- ---------------------------------------------------------------------------------------------
create table if not exists commission_rates (
  id          uuid primary key default gen_random_uuid(),
  -- The register's own role spelling, upper-cased with underscores, or 'ANY' for a rate that
  -- covers every role. A row for the exact role wins over ANY.
  role        text not null,
  -- The model as the Watu book spells it (A07, A06 ...), or 'ANY'.
  item        text not null,
  amount      numeric(14, 2) not null check (amount >= 0),
  updated_by  text,
  updated_at  timestamptz not null default now(),
  unique (role, item)
);
comment on table commission_rates is
  'What one sold phone earns, by role and model. ANY is the wildcard in either column; the most '
  'specific row wins. Edited from the commission pane -- never a constant in code, because a '
  'rate that needs a deploy to change is a rate somebody keeps in a spreadsheet instead.';

-- ---------------------------------------------------------------------------------------------
-- 2. THE RUN. One per period per kind, so a period cannot be paid twice by accident.
-- ---------------------------------------------------------------------------------------------
create table if not exists commission_runs (
  id            uuid primary key default gen_random_uuid(),
  -- 'YYYY-MM-DD' for the 9:00 AM daily schedule, 'YYYY-MM' for the monthly one (SOP A.1).
  period        text not null,
  kind          text not null default 'monthly' check (kind in ('daily', 'monthly')),

  status        text not null default 'draft'
                  check (status in ('draft', 'approved', 'paid', 'cancelled')),

  created_at    timestamptz not null default now(),
  created_by    text,
  built_at      timestamptz,

  -- SOP A.4: the Administration approval group signs off before any money moves.
  approved_by   text,
  approved_at   timestamptz,
  comment       text,

  -- SOP A.5 / A.7: the payment and its proof.
  paid_by       text,
  paid_at       timestamptz,
  payment_ref   text,
  -- SOP A.6: the stamp that stops the same period being paid a second time.
  cleared_at    timestamptz,

  -- SOP A, "Commission Audit Checklist ... must be completed and filed against every
  -- commission payment cycle". Five booleans, all of which must be true before Finance can
  -- record the payment -- the checklist is a gate, not a decoration.
  chk_unpaid_list    boolean not null default false,
  chk_watu_verified  boolean not null default false,
  chk_advance_topups boolean not null default false,
  chk_voucher        boolean not null default false,
  chk_bank_statement boolean not null default false,

  total_qty     integer not null default 0,
  total_amount  numeric(14, 2) not null default 0,
  -- Phones left OUT of the sheet because the sale is in dispute (SOP A.3).
  disqualified  integer not null default 0,

  updated_at    timestamptz not null default now(),

  unique (period, kind)
);
comment on table commission_runs is
  'One commission cycle. UNIQUE per (period, kind) and stamped cleared_at when paid, which is '
  'how Finance SOP A.6 -- "mark cleared immediately to prevent duplicate payment" -- is '
  'enforced by the database rather than by somebody remembering.';

create index if not exists commission_runs_period_idx on commission_runs (period desc);
create index if not exists commission_runs_status_idx on commission_runs (status) where status <> 'paid';

-- ---------------------------------------------------------------------------------------------
-- 3. THE PAYMENT SHEET, field for field from SOP A.4.
-- ---------------------------------------------------------------------------------------------
create table if not exists commission_lines (
  id           uuid primary key default gen_random_uuid(),
  run_id       uuid not null references commission_runs (id) on delete cascade,

  agent        text not null,         -- "agent name"
  agent_phone  text,                  -- "phone number"
  rsm          text,                  -- "the RSM the agent falls under"
  role         text,
  qty          integer not null,      -- "sales quantity"
  amount       numeric(14, 2) not null,   -- "commission amount"
  -- Phones this agent sold that were NOT paid for, and why (SOP A.3).
  disqualified integer not null default 0,
  note         text,
  unique (run_id, agent)
);
comment on table commission_lines is
  'The payment sheet rows: agent, quantity, amount, phone and the RSM they fall under -- the '
  'five fields Finance SOP A.4 requires. Written when the run is built and frozen thereafter, '
  'so the figure signed off on Tuesday is still the figure on Friday.';

create index if not exists commission_lines_run_idx on commission_lines (run_id);

-- ---------------------------------------------------------------------------------------------
-- 4. WHO IS TOLD. The Administration approval group (SOP A.4). Blank means nobody is emailed
--    and the pane is still the record.
-- ---------------------------------------------------------------------------------------------
insert into settings (key, value) values
  ('COMMISSION_EMAIL', '')
on conflict (key) do nothing;
