-- =============================================================================================
-- THE AUDIT LOG -- who did what, when, where, and what the value was before and after.
-- =============================================================================================
--   "Implement audit log tab too at admin - who did what what, when, where, value b4 and after
--    {auto-delete history of 15 days+}"
--
-- Safe to run more than once, and safe to run over an audit_log that already exists: the table
-- is created only if absent and every column is added only if absent.
--
-- WHY THE VALUE IS STORED AS A DIFF AND NOT AS THE ROW.
-- ---------------------------------------------------------------------------------------------
-- `before` and `after` hold ONLY the fields that actually changed, and only fields an explicit
-- allow-list in api/_lib/audit.js names. Storing the whole row would turn this table into a
-- second, unguarded copy of whatever it watched -- the payroll, the customer book -- readable by
-- anyone the audit nav is ever ticked for. A field nobody listed is not recorded, which is the
-- point: the default is silence, and adding a field is a deliberate line of code.
--
-- WHERE MEANS THE IP AND THE DEVICE, because that is the part of "where" a server can honestly
-- know. It is not a place on a map; it is what came with the request, and it is what tells an
-- admin that a code was used from somewhere it has never been used from before.
--
-- FIFTEEN DAYS, AND THE APP DOES THE DELETING.
-- ---------------------------------------------------------------------------------------------
-- The window is a setting (AUDIT_KEEP_DAYS, default 15) so it can be changed without a deploy.
-- The pruning runs from the application -- when the pane is opened, and at most hourly behind a
-- write -- because this project has no scheduler and a retention rule that depends on a cron
-- nobody set up is a retention rule that silently does not exist.
--
-- If you would rather have the database do it and pg_cron is enabled on your project, the very
-- last block of this file schedules it; it is commented out because pg_cron is off by default
-- and an extension that is not installed would abort the whole paste.
-- =============================================================================================

create table if not exists audit_log (
  id          bigint generated by default as identity primary key,
  at          timestamptz not null default now(),

  -- WHO
  actor_code  text,                      -- the access code that was signed in
  actor_name  text,
  actor_role  text,

  -- WHAT
  action      text not null,             -- the portal fn: saveRole, settingSet, advDecide, ...
  ref         text,                      -- the customer/loan reference, where the call had one
  team        text,
  subject     text,                      -- "code=GD role=STORE" -- which thing, never a payload

  -- HOW IT WENT
  ok          boolean not null default true,
  error       text,                      -- a REFUSED attempt is worth more than a successful one
  ms          integer
);

/* WHERE IT CAME FROM. Added separately from the create so an audit_log that predates this file
   gains them too -- which is the whole reason this migration can be run over an existing one. */
alter table audit_log add column if not exists ip  text;
alter table audit_log add column if not exists ua  text;

/* WHAT CHANGED. jsonb rather than two text columns: the diff is {field: value} for however many
   fields moved, and flattening that into a string would make it unreadable exactly when it is
   longest -- a role whose tabs were rewritten, an access code that gained three navs. */
alter table audit_log add column if not exists "before" jsonb;
alter table audit_log add column if not exists "after"  jsonb;

/* READ FROM THE TOP, ALWAYS. Every query this table serves is "newest first", so the index is
   descending; the other two are the filters the pane offers. */
create index if not exists audit_log_at_idx     on audit_log (at desc);
create index if not exists audit_log_actor_idx  on audit_log (actor_code, at desc);
create index if not exists audit_log_action_idx on audit_log (action, at desc);

/* THE RETENTION WINDOW, as a setting rather than a constant, so fifteen days can become thirty
   without a deploy. The app reads this; if the row is missing it uses 15. */
insert into settings (key, value)
values ('AUDIT_KEEP_DAYS', '15')
on conflict (key) do nothing;

comment on table audit_log is
  'Who did what, when, from where, and what changed. Pruned to AUDIT_KEEP_DAYS (default 15) by '
  'the application -- when the audit pane is opened, and at most hourly behind a write.';
comment on column audit_log."before" is
  'Only the fields that CHANGED, and only fields the allow-list in api/_lib/audit.js names. '
  'Never the whole row: this table must not become a second copy of what it watches.';
comment on column audit_log.ip is
  'The address the request arrived from. "Where" as a server can honestly know it.';

-- ---------------------------------------------------------------------------------------------
-- CLEAR THE BACKLOG NOW, if this table has been collecting since before the rule existed.
-- Safe to run on an empty table; safe to run twice.
-- ---------------------------------------------------------------------------------------------
delete from audit_log
where at < now() - (coalesce((select value from settings where key = 'AUDIT_KEEP_DAYS'), '15')
                    || ' days')::interval;

-- ---------------------------------------------------------------------------------------------
-- OPTIONAL: let the database do the pruning instead.
-- Only if pg_cron is enabled on your project (Database -> Extensions -> pg_cron). Uncomment the
-- three lines and run them on their own -- NOT as part of this file, because a missing extension
-- aborts the whole paste and you would not know which half had run.
--
--   create extension if not exists pg_cron;
--   select cron.schedule('audit-log-prune', '17 2 * * *',
--     $$delete from audit_log where at < now() - interval '15 days'$$);
--
-- The application prunes either way, so this is belt and braces, never the only thing keeping
-- the window honest.
-- ---------------------------------------------------------------------------------------------

-- DID IT LAND?
-- select column_name from information_schema.columns
--   where table_name = 'audit_log' and column_name in ('ip', 'ua', 'before', 'after');
