-- =============================================================================================
-- THE STAFF REGISTER AND THE ACCESS CODES, FILLED FROM STOCK -- the one-off backfill.
-- =============================================================================================
--   "please from new stock write me sql so that we pull all rsm or just always pull them auto
--    from new stock whenever they appear and auto insert them in access codes with autogenerated
--    code ... autofill staff table by matching rsm and agents from new stock and old stock data..
--    when we match rsm and agent on the same imei then thats done"
--
-- FROM NOW ON THE PANES DO THIS THEMSELVES: every time NEW STOCK or OLD STOCK opens under a code
-- that can write, any RSM or agent the stock names who is not yet a system user gets a staff row
-- (where the row carries a phone -- the register is keyed by it) and an access code with the RSM
-- or AGENT role and a freshly minted secret (syncStaffFromStock in api/portal.js). This file is
-- the same thing done ONCE, for everybody already on the lists today, so the Send form can choose
-- a receiver by role and name from the first morning rather than after somebody opens each pane.
--
-- Paste the WHOLE FILE into the Supabase SQL editor and run it once. Safe to re-run: every insert
-- skips what already exists -- by phone and by name for staff, by name (case- and space-folded)
-- for codes -- so a second run adds nobody and re-mints nothing. NOBODY IS DEMOTED: a name that
-- is an RSM on one row and an agent on another is an RSM. NOBODY IS EDITED: a staff row or a code
-- that exists is left exactly as it is. "SUPER AGENT" is the warehouse, not a person; blank,
-- numeric and two-letter names are spreadsheet noise, not people.
--
-- THE CODES ARE LIVE LOGINS the moment this runs, with whatever navs the RSM and AGENT roles have
-- ticked on the Roles card. Read them off the Access codes pane (chip: RSM / AGENT) and hand each
-- to its person; a code minted for somebody who has left is deleted there like any other.
-- Six characters from the same phone-safe alphabet a team code uses: no 0/O, no 1/I/L.
-- =============================================================================================

-- ---------------------------------------------------------------------------------------------
-- 1. WHO THE STOCK NAMES. One row per person: the two stock lists, RSMs and agents, best phone.
-- ---------------------------------------------------------------------------------------------
create temporary table if not exists _stock_people (
  name_key text primary key,     -- upper(name) with runs of space collapsed: the matching key
  name     text not null,        -- the spelling the stock uses (first seen)
  role     text not null,        -- 'RSM' | 'AGENT'
  phone    text,                 -- the last nine digits: how everything in HOOP matches a number
  manager  text                  -- for an agent: the RSM on the same row
);
truncate _stock_people;

with raw as (
  select rsm  as name, 'RSM'   as role, rsm_phone   as phone, null::text as manager from stock_audit
  union all
  select agent,        'AGENT',         agent_phone,          rsm                  from stock_audit
  union all
  select rsm,          'RSM',           rsm_phone,            null                 from old_stock
  union all
  select agent,        'AGENT',         agent_phone,          rsm                  from old_stock
),
clean as (
  select regexp_replace(upper(trim(name)), '\s+', ' ', 'g') as name_key,
         trim(name)                                          as name,
         role,
         -- +255 7.. / 255 7.. / 07.. / 7.. are one number: keep the last nine digits, and only
         -- where there ARE nine (a shorter scrawl is not a phone the register can be keyed on).
         case when length(regexp_replace(coalesce(phone, ''), '\D', '', 'g')) >= 9
              then right(regexp_replace(coalesce(phone, ''), '\D', '', 'g'), 9) end as digits,
         nullif(trim(manager), '')                            as manager
    from raw
   where name is not null
     and length(trim(name)) >= 3
     and trim(name) !~ '^[0-9\s\-\.\+\(\)]+$'
     and upper(trim(name)) not in ('N/A', 'NA', 'NONE', 'NULL', 'UNKNOWN', 'HAKUNA', 'SUPER AGENT', 'SUPERAGENT')
),
ranked as (
  -- RSM beats AGENT for the same name; a row with a phone beats one without.
  select distinct on (name_key)
         name_key, name,
         first_value(role) over (partition by name_key order by (role = 'RSM') desc) as role,
         first_value(digits) over (partition by name_key order by (digits is not null) desc) as digits,
         first_value(manager) over (partition by name_key order by (manager is not null) desc) as manager
    from clean
)
insert into _stock_people (name_key, name, role, phone, manager)
select name_key, name, role, digits, case when role = 'AGENT' then manager end
  from ranked;

-- ---------------------------------------------------------------------------------------------
-- 2. THE STAFF REGISTER. Only a person with a phone can have a row (phone is the key), and only
--    where neither that phone nor that name is already on it. Stored as the enrolment desk
--    stores it -- 0 followed by the nine digits -- so the two are one register, not two shapes.
-- ---------------------------------------------------------------------------------------------
insert into hoop_agents (phone, name, role, manager, active)
select '0' || p.phone, p.name,
       case when p.role = 'RSM' then 'Regional_Manager' else 'Field_Officer' end,
       p.manager, true
  from _stock_people p
 where p.phone is not null
   and not exists (select 1 from hoop_agents a
                    where right(regexp_replace(coalesce(a.phone, ''), '\D', '', 'g'), 9) = p.phone
                       or regexp_replace(upper(trim(coalesce(a.name, ''))), '\s+', ' ', 'g') = p.name_key)
on conflict (phone) do nothing;

-- ---------------------------------------------------------------------------------------------
-- 3. THE ACCESS CODES. One per name that has none, in the role the stock says, secret minted here.
-- ---------------------------------------------------------------------------------------------
do $$
declare
  p        record;
  alphabet constant text := '23456789ABCDEFGHJKMNPQRSTUVWXYZ';
  candidate text;
  i        integer;
  minted   integer := 0;
begin
  for p in
    select * from _stock_people sp
     where not exists (select 1 from access_codes c
                        where regexp_replace(upper(trim(coalesce(c.name, ''))), '\s+', ' ', 'g') = sp.name_key)
  loop
    loop
      candidate := '';
      for i in 1..6 loop
        candidate := candidate || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
      end loop;
      exit when not exists (select 1 from access_codes where upper(code) = candidate);
    end loop;
    insert into access_codes (code, name, role, teams, tabs)
    values (candidate, p.name, p.role, null, '{}')
    on conflict (code) do nothing;
    minted := minted + 1;
  end loop;
  raise notice 'access codes minted: %', minted;
end $$;

-- What was done, said out loud: how many people the stock names, how many now hold a code.
select
  (select count(*) from _stock_people)                                  as people_on_stock,
  (select count(*) from _stock_people where phone is null)              as without_phone_no_staff_row,
  (select count(*) from access_codes where upper(role) in ('RSM', 'AGENT')) as rsm_and_agent_codes_now;

drop table if exists _stock_people;
