import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { fakeDb } from './fake-db.mjs';
import { _FNS } from '../api/portal.js';

/* =========================================================================================
   COMMISSION -- the rate table, the run, the payment sheet, and the CLEARED stamp.

     Finance SOP A.1  the daily 9:00 AM and monthly schedules, generated by the system
     Finance SOP A.3  "Cross-check that each phone being paid for is correctly linked to the
                       agent who sold it, before approving payment"
     Finance SOP A.4  the payment sheet -- agent name, sales quantity, commission amount,
                       phone number, and the RSM the agent falls under -- forwarded to the
                       Administration approval group for sign-off
     Finance SOP A.6  "mark the payment as 'cleared' in the system IMMEDIATELY, to prevent
                       duplicate payment"
     Finance SOP A    the Commission Audit Checklist, filed against every payment cycle

   THE POINT IS A.6. The arithmetic could be done in a spreadsheet; what a spreadsheet cannot
   do is refuse to pay the same period twice.

   THE PERMISSION IS THE NAV. Nothing below names a Finance Manager or an Administrator.
   ========================================================================================= */
const FIN = { code: 'F1', name: 'JANETH', role: 'OFFICER', teams: null, tabs: ['commission'], readOnly: false };
const ADMIN_G = { code: 'D1', name: 'NEEMA M', role: 'OFFICER', teams: null, tabs: ['commappr'], readOnly: false };
const VIEWER = { code: 'V1', name: 'Auditor', role: 'AUDITOR', teams: null, tabs: ['commission', 'commappr'], readOnly: true };
const OTHER = { code: 'Z1', name: 'Mtu', role: 'OFFICER', teams: null, tabs: ['scorecards'], readOnly: false };
const OWNER = { code: 'X', name: 'Peter', role: 'ADMIN', teams: null, tabs: ['settings'], readOnly: false };

const MONTH = '2026-09';
const uid = tag => {
  const h = [...tag].reduce((a, c) => (a * 31 + c.charCodeAt(0)) >>> 0, 7).toString(16).padStart(8, '0');
  return `${h}-1111-4222-8333-${h}${h.slice(0, 4)}`;
};
const loan = (agent, o = {}) => ({ imei: o.imei || ('I' + agent + (o.n || 0)),
  disbursed_date: o.date || '2026-09-15', price: o.price == null ? 450000 : o.price,
  agent, model: o.model || 'A07' });
const sale = (imei, who) => ({ imei, sale_date: '2026-09-15', commission_agent: who, commission_phone: '0712000000' });
const rate = (role, item, amount) => ({ role, item, amount });
const reg = (name, role, branch, phone) => ({ name, role, branch, manager: null, phone: phone || ('07' + name.length) });
const aRun = o => ({ id: o.id, period: o.period || MONTH, kind: o.kind || 'monthly',
  status: o.status || 'draft', created_at: '2026-10-01T06:00:00Z', created_by: 'JANETH',
  built_at: '2026-10-01T06:00:00Z', approved_by: o.approvedBy || null, approved_at: o.approvedAt || null,
  comment: o.comment || null, paid_by: null, paid_at: null, payment_ref: null,
  cleared_at: o.clearedAt || null,
  chk_unpaid_list: false, chk_watu_verified: false, chk_advance_topups: false,
  chk_voucher: false, chk_bank_statement: false,
  total_qty: o.qty == null ? 10 : o.qty, total_amount: o.amount == null ? 100000 : o.amount,
  disqualified: o.disqualified || 0, updated_at: '2026-10-01T06:00:00Z' });
const cmDb = (o = {}) => fakeDb({
  commission_runs: o.runs || [], commission_lines: o.lines || [], commission_rates: o.rates || [],
  watu_loans: o.loans || [], hoop_sales: o.sales || [], hoop_agents: o.agents || [],
});
const ALL_CHECKS = { chkUnpaidList: true, chkWatuVerified: true, chkAdvanceTopups: true,
  chkVoucher: true, chkBankStatement: true };

/* ---------------------------------------------------------------------------------------- */
test('commission: building and signing off are two grants, and nobody holds both by accident', async () => {
  const d = cmDb({ runs: [aRun({ id: uid('r1') })] });
  const denied = async (fn, user, args) => {
    await assert.rejects(() => _FNS[fn](d, user, args || {}), e => e.status === 403,
      fn + ' must refuse a user who was never granted its pane');
  };
  // Finance builds and pays; it does not sign its own sheet off.
  await denied('commDecide', FIN, { id: uid('r1'), approve: true });
  // The approval group signs; it does not build, price or pay.
  await denied('commBuild', ADMIN_G, { period: MONTH });
  await denied('commPay', ADMIN_G, { id: uid('r1') });
  await denied('commRateSave', ADMIN_G, { role: 'ANY', item: 'ANY', amount: 1 });
  // Somebody with neither sees nothing at all.
  await denied('commRuns', OTHER); await denied('commRates', OTHER);
  await denied('commSheet', OTHER, { id: uid('r1') });
  // Both panes read each other's work -- that is the point of a sign-off.
  assert.ok(Array.isArray((await _FNS.commRuns(d, FIN, {})).rows));
  assert.ok(Array.isArray((await _FNS.commRuns(d, ADMIN_G, {})).rows));
  // View-only reads everything and moves no money.
  assert.ok((await _FNS.commRates(d, VIEWER)).rates);
  for (const [fn, args] of [['commBuild', { period: MONTH }], ['commDecide', { id: uid('r1'), approve: true }],
    ['commPay', { id: uid('r1'), paymentRef: 'X', checks: ALL_CHECKS }],
    ['commRateSave', { role: 'ANY', item: 'ANY', amount: 1 }]]) {
    await assert.rejects(() => _FNS[fn](d, VIEWER, args), e => e.status >= 400 && e.status < 500, fn);
  }
  assert.equal(d._dump('commission_runs')[0].status, 'draft');
  assert.ok((await _FNS.commRuns(d, OWNER, {})).rows, 'ADMIN IS FULL ACCESS EVERYWHERE');
});

test('commission: the navs are tickable, the money writes are audited, and the checklist is one list', () => {
  const src = fs.readFileSync(new URL('../api/portal.js', import.meta.url), 'utf8');
  const m = /const NAV_TABS = \[([^\]]+)\]/.exec(src);
  for (const k of ['commission', 'commappr']) assert.ok(m[1].includes(`'${k}'`), k + ' is a nav the owner can tick');
  for (const fn of ['commBuild', 'commDecide', 'commPay', 'commRateSave', 'commRateDelete']) {
    assert.match(src, new RegExp("AUDITED\\.add\\('" + fn + "'\\)"), fn + ' is audited: this is money leaving');
  }
  const sql = fs.readFileSync(new URL('../db/migrations/RUN-ME-2026-09-09-commission.sql', import.meta.url), 'utf8');
  for (const t of ['commission_rates', 'commission_runs', 'commission_lines']) {
    assert.match(sql, new RegExp('create table if not exists ' + t + ' \\('), t + ' is created idempotently');
  }
  assert.match(sql, /unique \(period, kind\)/, 'a period cannot be run twice, enforced by the database');
  assert.match(sql, /unique \(run_id, agent\)/, 'nor an agent paid twice inside one sheet');
  assert.match(sql, /cleared_at/, 'and SOP A.6 has a column of its own');
  // The five checklist rows the SOP names, in one place the pane and the gate both read.
  const checks = /const COMM_CHECKS = \[([\s\S]*?)\];/.exec(src);
  assert.ok(checks);
  for (const k of ['chk_unpaid_list', 'chk_watu_verified', 'chk_advance_topups', 'chk_voucher', 'chk_bank_statement']) {
    assert.ok(checks[1].includes(k), k + ' is on the checklist');
    assert.ok(sql.includes(k), k + ' is a column');
  }
});

/* ---------------------------------------------------------------------------------------- */
test('commission: a phone is priced by the seller\'s role and its model, most specific first', async () => {
  const d = cmDb({
    loans: [loan('ASHA', { n: 1, model: 'A07' }), loan('ASHA', { n: 2, model: 'A06' }),
      loan('JUMA', { n: 3, model: 'A07' }), loan('MOSES', { n: 4, model: 'A07' })],
    agents: [reg('SIMON', 'Regional_Manager', 'DAR'), reg('ASHA', 'Field_Officer', 'DAR'),
      reg('JUMA', 'Team_Leader', 'DAR'), reg('MOSES', 'Field_Officer', 'DAR')],
    rates: [
      rate('FIELD_OFFICER', 'A07', 10000),   // the exact pair
      rate('FIELD_OFFICER', 'ANY', 7000),    // this role, any model
      rate('ANY', 'A07', 5000),              // any role, this model
    ],
  });
  const r = await _FNS.commBuild(d, FIN, { period: MONTH, kind: 'monthly' });
  assert.equal(r.from, '2026-09-01'); assert.equal(r.to, '2026-09-30');
  const lines = d._dump('commission_lines');
  const asha = lines.find(l => l.agent === 'ASHA');
  assert.equal(asha.qty, 2);
  assert.equal(asha.amount, 10000 + 7000, 'the exact pair for the A07, the role wildcard for the A06');
  const juma = lines.find(l => l.agent === 'JUMA');
  assert.equal(juma.amount, 5000, 'no TEAM_LEADER rate, so the model wildcard');
  assert.equal(r.totalQty, 4);
  assert.equal(r.totalAmount, 10000 + 7000 + 5000 + 10000);
  // SOP A.4: the five fields are on the sheet.
  assert.equal(asha.agent_phone, '074'); assert.equal(asha.rsm, 'SIMON'); assert.equal(asha.role, 'Field_Officer');
  const [run] = d._dump('commission_runs');
  assert.equal(run.status, 'draft'); assert.equal(run.created_by, 'JANETH');
  assert.equal(run.period, MONTH); assert.equal(run.kind, 'monthly');
});

test('commission: an unpriced phone is NOT paid at zero -- it is reported as unpriced', async () => {
  const d = cmDb({
    loans: [loan('ASHA', { n: 1, model: 'A07' }), loan('ASHA', { n: 2, model: 'S24' })],
    agents: [reg('ASHA', 'Field_Officer', 'DAR')],
    rates: [rate('FIELD_OFFICER', 'A07', 10000)],
  });
  const r = await _FNS.commBuild(d, FIN, { period: MONTH });
  assert.equal(r.totalQty, 1, 'only the phone somebody priced');
  assert.equal(r.totalAmount, 10000);
  assert.equal(r.disqualified, 1);
  const [line] = d._dump('commission_lines');
  assert.equal(line.disqualified, 1);
  assert.match(line.note, /hazina kiwango|unpriced/, 'and the sheet says why, so Finance can go and price it');
  // No rate table at all: nothing is paid and everything is reported.
  const bare = cmDb({ loans: [loan('ASHA')], agents: [reg('ASHA', 'Field_Officer', 'DAR')] });
  const r2 = await _FNS.commBuild(bare, FIN, { period: MONTH });
  assert.equal(r2.totalAmount, 0); assert.equal(r2.disqualified, 1);
});

test('commission: SOP A.3 -- a phone the shop credits to somebody else is not paid this cycle', async () => {
  const d = cmDb({
    loans: [loan('ASHA', { n: 1, imei: 'I1' }), loan('ASHA', { n: 2, imei: 'I2' }), loan('ASHA', { n: 3, imei: 'I3' })],
    // The shop's own book: I2 was actually sold by somebody else.
    sales: [sale('I1', 'ASHA MOHAMED'), sale('I2', 'JUMA KAZI'), sale('I3', 'ASHA')],
    agents: [reg('ASHA', 'Field_Officer', 'DAR')],
    rates: [rate('ANY', 'ANY', 8000)],
  });
  const r = await _FNS.commBuild(d, FIN, { period: MONTH });
  assert.equal(r.totalQty, 2, 'the disputed phone is held back');
  assert.equal(r.totalAmount, 16000);
  assert.equal(r.disqualified, 1);
  const [line] = d._dump('commission_lines');
  assert.match(line.note, /mgogoro|disputed/);
  assert.equal(line.disqualified, 1);
  // A name that overlaps is the same person, not a dispute: "ASHA" and "ASHA MOHAMED".
  assert.equal(line.qty, 2);
  // A loan with nobody named on it is nobody's commission.
  const nameless = cmDb({ loans: [{ imei: 'X', disbursed_date: '2026-09-10', price: 1, agent: null, model: 'A07' }],
    rates: [rate('ANY', 'ANY', 8000)] });
  const r2 = await _FNS.commBuild(nameless, FIN, { period: MONTH });
  assert.equal(r2.totalQty, 0); assert.equal(r2.disqualified, 1);
  assert.equal(nameless._dump('commission_lines').length, 0);
});

test('commission: the daily 9am schedule is a day and the monthly one is a month (SOP A.1)', async () => {
  const d = cmDb({
    loans: [loan('ASHA', { n: 1, date: '2026-09-15' }), loan('ASHA', { n: 2, date: '2026-09-16' })],
    agents: [reg('ASHA', 'Field_Officer', 'DAR')], rates: [rate('ANY', 'ANY', 1000)],
  });
  const day = await _FNS.commBuild(d, FIN, { period: '2026-09-15', kind: 'daily' });
  assert.equal(day.from, '2026-09-15'); assert.equal(day.to, '2026-09-15'); assert.equal(day.totalQty, 1);
  const month = await _FNS.commBuild(d, FIN, { period: MONTH, kind: 'monthly' });
  assert.equal(month.totalQty, 2);
  assert.equal(d._dump('commission_runs').length, 2, 'a day and a month are different cycles');
  // The period must match the kind.
  await assert.rejects(() => _FNS.commBuild(d, FIN, { period: MONTH, kind: 'daily' }), e => e.status === 400);
  await assert.rejects(() => _FNS.commBuild(d, FIN, { period: '2026-09-15', kind: 'monthly' }), e => e.status === 400);
  await assert.rejects(() => _FNS.commBuild(d, FIN, { period: 'soon' }), e => e.status === 400);
});

test('commission: a draft may be rebuilt; a signed sheet may not', async () => {
  const d = cmDb({
    loans: [loan('ASHA', { n: 1 })], agents: [reg('ASHA', 'Field_Officer', 'DAR')],
    rates: [rate('ANY', 'ANY', 5000)],
  });
  await _FNS.commBuild(d, FIN, { period: MONTH });
  assert.equal(d._dump('commission_runs')[0].total_amount, 5000);
  // A second phone lands, and the draft is rebuilt to match.
  d._dump('watu_loans').push(loan('ASHA', { n: 2 }));
  await _FNS.commBuild(d, FIN, { period: MONTH });
  assert.equal(d._dump('commission_runs').length, 1, 'rebuilt, not duplicated');
  assert.equal(d._dump('commission_runs')[0].total_amount, 10000);
  assert.equal(d._dump('commission_lines').length, 1, 'and the old lines were replaced, not added to');
  assert.equal(d._dump('commission_lines')[0].qty, 2);
  // Signed off: the figure is frozen, whatever lands afterwards.
  const id = String(d._dump('commission_runs')[0].id);
  await _FNS.commDecide(d, ADMIN_G, { id, approve: true });
  d._dump('watu_loans').push(loan('ASHA', { n: 3 }));
  await assert.rejects(() => _FNS.commBuild(d, FIN, { period: MONTH }),
    e => e.status === 400 && /idhinishwa|signed off/i.test(e.message));
  assert.equal(d._dump('commission_runs')[0].total_amount, 10000, 'the signed figure did not move');
});

/* ---------------------------------------------------------------------------------------- */
test('commission: the sign-off, and sending a sheet back to Finance', async () => {
  const d = cmDb({ runs: [aRun({ id: uid('s1') })] });
  await assert.rejects(() => _FNS.commDecide(d, ADMIN_G, { id: uid('s1'), approve: false }),
    e => e.status === 400 && /sababu|reason/i.test(e.message), 'sending it back needs a reason');
  const r = await _FNS.commDecide(d, ADMIN_G, { id: uid('s1'), approve: true });
  assert.equal(r.status, 'approved');
  const [row] = d._dump('commission_runs');
  assert.equal(row.approved_by, 'NEEMA M'); assert.ok(row.approved_at);
  // Sent back: the sign-off is cleared so Finance can rebuild.
  const r2 = await _FNS.commDecide(d, ADMIN_G, { id: uid('s1'), approve: false, comment: 'Kiwango cha A06 si sahihi' });
  assert.equal(r2.status, 'draft');
  assert.equal(row.approved_by, null); assert.equal(row.approved_at, null);
  assert.equal(row.comment, 'Kiwango cha A06 si sahihi');
  // An empty sheet is not something to sign.
  const empty = cmDb({ runs: [aRun({ id: uid('s2'), qty: 0, amount: 0 })] });
  await assert.rejects(() => _FNS.commDecide(empty, ADMIN_G, { id: uid('s2'), approve: true }),
    e => e.status === 400 && /tupu|nothing on this sheet/i.test(e.message));
  await assert.rejects(() => _FNS.commDecide(d, ADMIN_G, { id: uid('zz'), approve: true }), e => e.status === 400);
});

test('commission: the audit checklist is a GATE, not a decoration', async () => {
  const mk = () => cmDb({ runs: [aRun({ id: uid('p1'), status: 'approved', approvedBy: 'NEEMA M', approvedAt: '2026-10-01T07:00:00Z' })] });
  // Not signed off yet: no payment at all.
  const draft = cmDb({ runs: [aRun({ id: uid('p1') })] });
  await assert.rejects(() => _FNS.commPay(draft, FIN, { id: uid('p1'), paymentRef: 'TX1', checks: ALL_CHECKS }),
    e => e.status === 400 && /idhini|sign-off/i.test(e.message));
  // No reference: SOP A.7 has nothing to file.
  const d = mk();
  await assert.rejects(() => _FNS.commPay(d, FIN, { id: uid('p1'), checks: ALL_CHECKS }),
    e => e.status === 400 && /kumbukumbu|reference/i.test(e.message));
  // Four of five ticked is not a completed checklist, and the message says which is missing.
  for (const miss of Object.keys(ALL_CHECKS)) {
    const partial = { ...ALL_CHECKS }; delete partial[miss];
    await assert.rejects(() => _FNS.commPay(mk(), FIN, { id: uid('p1'), paymentRef: 'TX1', checks: partial }),
      e => e.status === 400 && /ukaguzi|checklist/i.test(e.message), 'missing ' + miss);
  }
  assert.equal(d._dump('commission_runs')[0].status, 'approved', 'and nothing was paid');
  // All five, with a reference: paid AND cleared in the same write.
  const ok = mk();
  const r = await _FNS.commPay(ok, FIN, { id: uid('p1'), paymentRef: 'TX-9911', checks: ALL_CHECKS });
  assert.equal(r.status, 'paid'); assert.ok(r.clearedAt);
  const [row] = ok._dump('commission_runs');
  assert.equal(row.status, 'paid'); assert.equal(row.paid_by, 'JANETH');
  assert.equal(row.payment_ref, 'TX-9911'); assert.ok(row.cleared_at);
  for (const c of ['chk_unpaid_list', 'chk_watu_verified', 'chk_advance_topups', 'chk_voucher', 'chk_bank_statement']) {
    assert.equal(row[c], true, c + ' is recorded against the cycle, not just ticked on a screen');
  }
});

test('commission: SOP A.6 -- a cleared cycle can never be paid a second time', async () => {
  const d = cmDb({ runs: [aRun({ id: uid('c1'), status: 'approved', approvedBy: 'NEEMA M' })] });
  await _FNS.commPay(d, FIN, { id: uid('c1'), paymentRef: 'TX-1', checks: ALL_CHECKS });
  await assert.rejects(() => _FNS.commPay(d, FIN, { id: uid('c1'), paymentRef: 'TX-2', checks: ALL_CHECKS }),
    e => e.status === 400 && /A\.6/.test(e.message) && /mara ya pili|twice/i.test(e.message));
  assert.equal(d._dump('commission_runs')[0].payment_ref, 'TX-1', 'the first payment stands');
  // Nor can it be signed back down and re-run.
  await assert.rejects(() => _FNS.commDecide(d, ADMIN_G, { id: uid('c1'), approve: false, comment: 'oops' }),
    e => e.status === 400 && /imelipwa|already been paid/i.test(e.message));
  await assert.rejects(() => _FNS.commBuild(d, FIN, { period: MONTH }), e => e.status === 400);
  /* AND THE RACE: two people pressing Pay at the same instant. The guarded update matches
     nothing for the second, which is exactly what cleared_at is for. */
  const race = cmDb({ runs: [aRun({ id: uid('c2'), status: 'approved', approvedBy: 'NEEMA M' })] });
  const raw = race.from.bind(race);
  let armed = true;
  race.from = name => {
    const q = raw(name);
    if (name === 'commission_runs' && armed) {
      const u = q.update.bind(q);
      q.update = p => { armed = false; race._dump('commission_runs')[0].cleared_at = '2026-10-01T09:00:00Z';
        race._dump('commission_runs')[0].status = 'paid'; return u(p); };
    }
    return q;
  };
  await assert.rejects(() => _FNS.commPay(race, FIN, { id: uid('c2'), paymentRef: 'TX-3', checks: ALL_CHECKS }),
    e => e.status === 400 && /A\.6/.test(e.message));
});

/* ---------------------------------------------------------------------------------------- */
test('commission: rates are edited from the pane, and the sheet reads back whole', async () => {
  const d = cmDb({ agents: [reg('ASHA', 'Field_Officer', 'DAR')], loans: [loan('ASHA')] });
  await _FNS.commRateSave(d, FIN, { role: ' field officer ', item: ' a07 ', amount: '12000' });
  const [r] = d._dump('commission_rates');
  assert.equal(r.role, 'FIELD_OFFICER'); assert.equal(r.item, 'A07'); assert.equal(r.amount, 12000);
  assert.equal(r.updated_by, 'JANETH');
  // Saving the same pair corrects it rather than adding a second.
  await _FNS.commRateSave(d, FIN, { role: 'FIELD_OFFICER', item: 'A07', amount: 9000 });
  assert.equal(d._dump('commission_rates').length, 1);
  assert.equal(d._dump('commission_rates')[0].amount, 9000);
  // Blank means the wildcard, which is how a single company-wide rate is set.
  await _FNS.commRateSave(d, FIN, { amount: 3000 });
  assert.ok(d._dump('commission_rates').some(x => x.role === 'ANY' && x.item === 'ANY'));
  await assert.rejects(() => _FNS.commRateSave(d, FIN, { role: 'ANY', item: 'ANY' }), e => e.status === 400);
  await assert.rejects(() => _FNS.commRateSave(d, FIN, { role: 'ANY', item: 'ANY', amount: -5 }), e => e.status === 400);
  await _FNS.commRateDelete(d, FIN, { role: 'FIELD_OFFICER', item: 'A07' });
  assert.equal(d._dump('commission_rates').length, 1);
  await assert.rejects(() => _FNS.commRateDelete(d, FIN, { role: 'FIELD_OFFICER' }), e => e.status === 400);
  // And the sheet: the run, its lines, and the checklist labels the pane draws.
  await _FNS.commBuild(d, FIN, { period: MONTH });
  const id = String(d._dump('commission_runs')[0].id);
  const s = await _FNS.commSheet(d, ADMIN_G, { id });
  assert.equal(s.run.period, MONTH); assert.equal(s.run.status, 'draft');
  assert.equal(s.lines.length, 1); assert.equal(s.lines[0].agent, 'ASHA');
  assert.equal(s.checks.length, 5);
  assert.ok(s.checks.every(c => c.key && c.label));
  await assert.rejects(() => _FNS.commSheet(d, FIN, { id: 'nope' }), e => e.status === 400);
});

test('commission: before the migration every pane says which file to run', async () => {
  const bare = fakeDb({ commission_runs: [], commission_rates: [], commission_lines: [],
    watu_loans: [], hoop_agents: [], hoop_sales: [] },
    { missingColumns: { commission_runs: ['id'], commission_rates: ['role'] } });
  assert.equal((await _FNS.commRuns(bare, FIN, {})).notReady, true);
  assert.equal((await _FNS.commRates(bare, FIN)).notReady, true);
  assert.equal((await _FNS.commSheet(bare, FIN, { id: uid('x') })).notReady, true);
  for (const [fn, user, args] of [
    ['commBuild', FIN, { period: MONTH }],
    ['commDecide', ADMIN_G, { id: uid('x'), approve: true }],
    ['commPay', FIN, { id: uid('x'), paymentRef: 'T', checks: ALL_CHECKS }],
    ['commRateSave', FIN, { role: 'ANY', item: 'ANY', amount: 1 }],
  ]) {
    await assert.rejects(() => _FNS[fn](bare, user, args),
      e => e.status === 400 && /RUN-ME-2026-09-09-commission\.sql/.test(e.message), fn + ' names the migration');
  }
});
