package com.samaritantechs.hooploanlock;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;

import org.json.JSONObject;

import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;

/**
 * THE MARK ON THE LOCKED SCREEN, SENT BY THE OFFICE INSTEAD OF COMPILED IN.
 *
 *   "For hope phones this is the logo, so the logos differ"
 *
 * One APK serves two companies. HOPE runs this signed build deliberately, so that no second
 * app has to be kept, signed and distributed -- and every WORD on the lock screen already
 * comes from the server, so it reads HOPE. The wordmark did not: it was
 * R.drawable.hoop_logo_white, compiled in, so a locked HOPE handset drew HOOP's mark directly
 * above the words "HOPE MICROCREDIT".
 *
 * Two companies on one screen is worse than no logo at all. The person holding that phone is
 * deciding whether this is their employer or somebody's scam, and the mark is what they read
 * before any sentence.
 *
 * WHY THE FILE IS CACHED AND NOT FETCHED WHEN THE SCREEN IS DRAWN. The case this whole
 * feature exists for is a handset that locks itself in a dead spot on the offline grace: it
 * draws the lock screen with NO network, from whatever it last stored. A logo fetched at draw
 * time would be missing on exactly the phone that most needs to say who is holding it. So the
 * bytes are downloaded on a BEAT -- which by definition has a network -- and the screen only
 * ever reads the local file.
 *
 * AND ONLY WHEN THEY CHANGED. `logoVersion` is generated by the server from the file's own
 * bytes, so an unchanged mark costs nothing after the first fetch. Three hundred handsets
 * beating every fifteen minutes re-downloading 16 KB would be about 480 MB a month on data
 * the company pays for; this is 16 KB, once, per change.
 *
 * NOTHING HERE MAY BREAK A BEAT. A lock order arriving is worth incomparably more than a
 * logo, so every failure below is swallowed and simply retried on the next beat -- the
 * handset keeps whatever mark it already had in the meantime.
 */
final class LockLogo {

    /** Cap: a mark is a wordmark, and anything larger is a mistake or a wrong URL. */
    private static final int MAX_BYTES = 2 * 1024 * 1024;
    private static final int TIMEOUT_MS = 12000;

    /** What the server says when it wants NO mark drawn at all -- see apply(). */
    static final String NONE = "none";

    private LockLogo() { }

    static File file(Context c) {
        return new File(c.getFilesDir(), "lock-logo.png");
    }

    /**
     * Take whatever this beat said about the mark.
     *
     * THREE ANSWERS, AND THE DIFFERENCE BETWEEN THE FIRST TWO IS THE WHOLE POINT:
     *
     *   the field is ABSENT   an older deployment that has never heard of this. Change
     *                         nothing: it must go on drawing the mark compiled into it,
     *                         exactly as it did before this class existed. HOOP's phones are
     *                         in this state until HOOP publishes a mark of its own.
     *   the field is NULL     the office deliberately says NO MARK. Draw nothing -- never
     *                         fall back to the compiled one, because falling back is
     *                         precisely how HOOP's logo lands on a HOPE phone. It is also
     *                         what a released handset is told, so our mark does not stay
     *                         cached on a former employee's phone.
     *   an address            fetch it if the version moved, and draw it from then on.
     */
    static void apply(Context c, JSONObject r) {
        try {
            if (r == null || !r.has("logo")) return;               // older server: leave it be
            if (r.isNull("logo")) { forget(c); return; }

            String where = r.optString("logo", "").trim();
            if (where.isEmpty()) { forget(c); return; }
            String version = r.optString("logoVersion", "").trim();
            if (version.isEmpty()) version = where;                // no version: the address is one

            String held = Prefs.str(c, Prefs.LOGO_VERSION, "");
            if (version.equals(held) && file(c).exists()) return;  // already holding these bytes

            if (download(c, resolve(c, where))) {
                Prefs.put(c, Prefs.LOGO_VERSION, version);
            }
            // A failed fetch writes no version, so the next beat simply tries again -- and the
            // handset goes on drawing whatever it had rather than nothing.
        } catch (Throwable ignored) {
            // See the class note: a logo may never cost a beat.
        }
    }

    /**
     * A RELATIVE PATH IS RESOLVED AGAINST THIS HANDSET'S OWN SERVER, and that single line is
     * what lets one APK serve both companies: HOPE's phones fetch HOPE's mark from HOPE and
     * Hoop's fetch Hoop's from Hoop, off identical code. An absolute URL is honoured as given,
     * for an office that keeps its art somewhere else.
     */
    private static String resolve(Context c, String where) {
        if (where.regionMatches(true, 0, "http", 0, 4)) return where;
        return Prefs.server(c) + (where.startsWith("/") ? where : "/" + where);
    }

    /** Straight to a temp file and renamed on success, so a half-written mark is never drawn. */
    private static boolean download(Context c, String url) throws Exception {
        HttpURLConnection conn = null;
        File tmp = new File(c.getFilesDir(), "lock-logo.part");
        try {
            conn = (HttpURLConnection) new URL(url).openConnection();
            conn.setConnectTimeout(TIMEOUT_MS);
            conn.setReadTimeout(TIMEOUT_MS);
            if (conn.getResponseCode() != 200) return false;

            boolean tooBig = false;
            // try-with-resources: a handset that hits the cap or a mid-read failure must not
            // also leak the descriptor -- this runs on every beat where the version moved.
            try (InputStream in = conn.getInputStream();
                 FileOutputStream out = new FileOutputStream(tmp)) {
                byte[] buf = new byte[8192];
                int n, total = 0;
                while ((n = in.read(buf)) > 0) {
                    total += n;
                    if (total > MAX_BYTES) { tooBig = true; break; }
                    out.write(buf, 0, n);
                }
            }
            if (tooBig) return false;      // the finally below removes the part file

            /* AND IT HAS TO BE A PICTURE. A captive-portal login page answers 200 with HTML,
               and a handset on hotel wifi would otherwise cache that as its company logo and
               draw nothing for ever after. Decoding bounds only -- no pixels allocated. */
            BitmapFactory.Options probe = new BitmapFactory.Options();
            probe.inJustDecodeBounds = true;
            BitmapFactory.decodeFile(tmp.getAbsolutePath(), probe);
            if (probe.outWidth <= 0 || probe.outHeight <= 0) { tmp.delete(); return false; }

            File dest = file(c);
            dest.delete();
            return tmp.renameTo(dest);
        } finally {
            if (conn != null) conn.disconnect();
            if (tmp.exists()) tmp.delete();
        }
    }

    /** Told "no mark": drop the bytes and REMEMBER that we were told, which is not the same
        as never having been told. See apply() and bitmap(). */
    private static void forget(Context c) {
        file(c).delete();
        Prefs.put(c, Prefs.LOGO_VERSION, NONE);
    }

    /**
     * Has the office said to draw NO mark at all?
     *
     * Asked separately from bitmap() because "no mark" and "no mark yet" are different
     * answers with different right behaviours, and folding them into one return value is how
     * the wrong company's logo ends up on a screen. Never told: fall back to the build's own
     * mark, which is what every HOOP handset does today. Told none: draw nothing.
     */
    static boolean suppressed(Context c) {
        try {
            return NONE.equals(Prefs.str(c, Prefs.LOGO_VERSION, ""));
        } catch (Throwable ignored) {
            return false;
        }
    }

    /** The cached mark, or null for "nothing stored -- use the one compiled into this build". */
    static Bitmap bitmap(Context c) {
        try {
            File f = file(c);
            if (!f.exists()) return null;
            return BitmapFactory.decodeFile(f.getAbsolutePath());  // null if unreadable: fall back
        } catch (Throwable ignored) {
            return null;
        }
    }
}
